# Generated by Django 2.2.26 on 2022-03-16 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_image')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tasks_posted', models.IntegerField(default=0)),
                ('tasks_received', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=5, unique=True)),
                ('task_title', models.CharField(max_length=30)),
                ('completion_state', models.BooleanField(default=0)),
                ('task_description', models.TextField()),
                ('task_reward', models.IntegerField(default=0)),
                ('release_time', models.DateTimeField(auto_now_add=True)),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='task.UserProfile')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve', to='task.UserProfile')),
            ],
        ),
    ]
