# Generated by Django 2.2.26 on 2022-03-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='receiver_id',
            new_name='receiver',
        ),
    ]
