# Generated by Django 2.2.26 on 2022-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20220316_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_state',
            field=models.BooleanField(default=0),
        ),
    ]
